language: python
cache: pip

python:
  - "3.5"
  - "3.4"
  - "2.7"

branches:
  only:
    - master

before_install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements-test.txt
  - flake8
  - isort --check-only --recursive .

install:
  - python setup.py -q develop

before_script:
  - mkdir docs/source/_static
  - sphinx-build -W -b html docs/source docs/_build

script:
  - nosetests --with-coverage --cover-package=netjsonconfig
  - |
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      # gets commit message of last commit before pull request merge
      COMMIT_MESSAGE=$(git log $TRAVIS_PULL_REQUEST_SHA --format=%B -n 1)
      printf "Checking commit message:\n\n"
      printf "$COMMIT_MESSAGE\n\n"
      checkcommit --message "$COMMIT_MESSAGE"
    fi

after_success:
  coveralls
